# https://www.npmjs.com/package/eslint-config-moon-node
root: true
extends: ["moon", "moon/node"]
parserOptions:
  project: tsconfig.test.json
settings:
  jest:
    version: 1
ignorePatterns: ["cjs", "tests/*.mjs", "tests/*.mjs.*"]
