# https://www.npmjs.com/package/eslint-config-moon
root: true
extends: ['moon', 'moon/node', 'plugin:json/recommended']
parserOptions:
  project: tsconfig.test.json
plugins:
  - '@stylistic/eslint-plugin-ts'
  - 'json'
settings:
  jest:
    version: 1
ignorePatterns: ['cjs', 'tests/*.mjs', 'tests/*.mjs.*']
overrides:
  - files: '*.json'
    rules:
      comma-dangle: 2
