# for each key in npmRegistries, prepend "https:", assign to npmRegistryServer, and publish.
npmRegistries:
  //npm.pkg.github.com: {}
  # "just a reverse proxy to registry.npmjs.org" - https://github.com/yarnpkg/yarn/issues/889#issuecomment-253237639
  # later, replaced with a CNAME (https://toolbox.googleapps.com/apps/dig/#CNAME/registry.yarnpkg.com)
  //registry.yarnpkg.com: {}
packageExtensions:
  '@amanda-mitchell/semantic-release-npm-multiple@3.16.0':
    peerDependencies:
      semantic-release: '>=19'
