import { deepStrictEqual, ok } from 'node:assert/strict'
import { existsSync, readdirSync, rmSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { describe, it } from 'node:test'
import {
  EvaluationOptions,
  MSBuildProject as MSBP,
} from '../../src/dotnet/MSBuildProject.js'

export const {
  DeterministicNupkgCsproj: DeterministicNupkgCsproj,
  SignAfterPackCsproj: SignAfterPackCsproj,
} = await MSBP.PackableProjectsToMSBuildProjects([
  resolve(import.meta.dirname, '../../dotnet/samples/HCE.Shared.DeterministicNupkg/HCE.Shared.DeterministicNupkg.csproj'),
  resolve(import.meta.dirname, '../../dotnet/samples/HCE.Shared.SignAfterPack/HCE.Shared.SignAfterPack.csproj'),
]).then((v: MSBP[]) => {
  return Object.freeze({
    DeterministicNupkgCsproj: Object.freeze(v[0]),
    SignAfterPackCsproj: Object.freeze(v[1]),
  })
})

await it('is built', async () =>
  deepStrictEqual(
    JSON.stringify(Object.entries(await import('@halospv3/hce.shared-config/dotnet/MSBuildProject')), undefined, 2),
    JSON.stringify(Object.entries(await import('../../src/dotnet/MSBuildProject.js')), undefined, 2),
  ),
)

await describe('MSBuildProject', async () => {
  await describe('MatrixProperties', async (ctx1) => {
    await it('has expected name', async () => {
      ok(ctx1.name in MSBP)
    })
    await it('is array of expected values', async () => {
      deepStrictEqual(
        MSBP.MatrixProperties,
        [
          'TargetFramework',
          'TargetFrameworks',
          'RuntimeIdentifier',
          'RuntimeIdentifiers',
        ],
      )
    })
  })
  await describe('Evaluate', async (c00) => {
    await it('has expected name', () => {
      deepStrictEqual(MSBP.Evaluate.name, c00.name)
    })
    await it('may return expected object (HCE.Shared.DeterministicNupkg)', async () => {
      const deterministicNupkgProj = resolve(import.meta.dirname, '../../dotnet/samples/HCE.Shared.DeterministicNupkg/HCE.Shared.DeterministicNupkg.csproj')
      const pakDir = resolve(dirname(deterministicNupkgProj), 'packages')
      if (existsSync(pakDir) && readdirSync(pakDir).some(v => v.endsWith('.nupkg') || v.endsWith('.snupkg')))
        rmSync(pakDir, { recursive: true, force: true })
      const evalOpts: EvaluationOptions = new EvaluationOptions({
        FullName: deterministicNupkgProj,
        GetItem: [],
        GetProperty: [...MSBP.MatrixProperties],
        GetTargetResult: [],
        Property: {},
        Targets: ['Restore', 'Pack'],
      })
      const actual: MSBP = await MSBP.Evaluate(evalOpts)
      const expected = new MSBP({
        fullPath: deterministicNupkgProj,
        projTargets: [
          'AddDepsJsonAndRuntimeConfigToCopyItemsForReferencingProjects',
          'AddDepsJsonAndRuntimeConfigToPublishItemsForReferencingProjects',
          'AddImplicitDefineConstants',
          'AddRuntimeConfigFileToBuiltProjectOutputGroupOutput',
          'AddSourceRevisionToInformationalVersion',
          'AddTransitiveFrameworkReferences',
          'AddWinRTComponentImplementationReference',
          'AddWindowsSdkKnownFrameworkReferences',
          'AdjustDefaultPlatformTargetForNetFrameworkExeWithNoNativeCopyLocalItems',
          'AfterBuild',
          'AfterClean',
          'AfterCompile',
          'AfterPublish',
          'AfterRebuild',
          'AfterResGen',
          'AfterResolveReferences',
          'AfterSdkPublish',
          'AllProjectOutputGroups',
          'AllProjectOutputGroupsDependencies',
          'ApplyImplicitVersions',
          'AssignLinkMetadata',
          'AssignProjectConfiguration',
          'AssignTargetPaths',
          'BeforeBuild',
          'BeforeClean',
          'BeforeCompile',
          'BeforePublish',
          'BeforeRebuild',
          'BeforeResGen',
          'BeforeResolveReferences',
          'Build',
          'BuildCompile',
          'BuildCompileTraverse',
          'BuildGenerateSources',
          'BuildGenerateSourcesTraverse',
          'BuildLink',
          'BuildLinkTraverse',
          'BuildOnlySettings',
          'BuildProject',
          'BuiltProjectOutputGroup',
          'BuiltProjectOutputGroupDependencies',
          'CheckForDuplicateItems',
          'CheckForImplicitPackageReferenceOverrides',
          'Clean',
          'CleanAppxPackage',
          'CleanPublishFolder',
          'CleanReferencedProjects',
          'CollectApiCompatInputs',
          'CollectCentralPackageVersions',
          'CollectFrameworkReferences',
          'CollectNuGetAuditSuppressions',
          'CollectPackageDownloads',
          'CollectPackageReferences',
          'CollectReferencedNuGetPackages',
          'CollectResolvedSDKReferencesDesignTime',
          'CollectSDKReferencesDesignTime',
          'Compile',
          'CompileLicxFiles',
          'ComposeStore',
          'ComputeAndCopyFilesToPublishDirectory',
          'ComputeAndCopyFilesToStoreDirectory',
          'ComputeContainerBaseImage',
          'ComputeContainerConfig',
          'ComputeDependencyFileCompilerOptions',
          'ComputeEmbeddedApphostPaths',
          'ComputeFilesCopiedToPublishDir',
          'ComputeFilesToPublish',
          'ComputeFilesToStore',
          'ComputeIntermediateSatelliteAssemblies',
          'ComputeRefAssembliesToPublish',
          'ComputeResolvedFilesToPublishList',
          'ContentFilesProjectOutputGroup',
          'CopyAdditionalFiles',
          'CopyFilesToOutputDirectory',
          'CopyFilesToPublishDirectory',
          'CopyFilesToStoreDirectory',
          'CopyRunEnvironmentFiles',
          'CoreBuild',
          'CoreClean',
          'CoreCompile',
          'CoreGenerateAssemblyInfo',
          'CoreGenerateSatelliteAssemblies',
          'CoreResGen',
          'CreateCompilerGeneratedFilesOutputPath',
          'CreateCustomManifestResourceNames',
          'CreateGeneratedAssemblyInfoInputsCacheFile',
          'CreateManifestResourceNames',
          'CreateReadyToRunImages',
          'CreateSatelliteAssemblies',
          'DebugSymbolsProjectOutputGroup',
          'DebugSymbolsProjectOutputGroupDependencies',
          'DefaultCopyToPublishDirectoryMetadata',
          'DesignTimeResolveAssemblyReferences',
          'DesignerRuntimeImplementationProjectOutputGroup',
          'DocumentationProjectOutputGroup',
          'DocumentationProjectOutputGroupDependencies',
          'EnableIntermediateOutputPathMismatchWarning',
          'EnsureNETCoreAppRuntime',
          'ExecNupkgDeterministicator',
          'ExpandSDKReferences',
          'ExpandSDKReferencesDesignTime',
          'ExportWindowsMDFile',
          'FindInvalidProjectReferences',
          'FindReferenceAssembliesForReferences',
          'GenerateAdditionalSources',
          'GenerateApplicationManifest',
          'GenerateAssemblyInfo',
          'GenerateBindingRedirects',
          'GenerateBindingRedirectsUpdateAppConfig',
          'GenerateBuildDependencyFile',
          'GenerateBuildRuntimeConfigurationFiles',
          'GenerateDeploymentManifest',
          'GenerateGlobalUsings',
          'GenerateMSBuildEditorConfigFile',
          'GenerateMSBuildEditorConfigFileCore',
          'GenerateMSBuildEditorConfigFileShouldRun',
          'GenerateManifests',
          'GenerateNETCompatibleDefineConstants',
          'GenerateNuspec',
          'GeneratePlatformCompatibleDefineConstants',
          'GeneratePublishDependencyFile',
          'GenerateRestoreGraphFile',
          'GenerateSatelliteAssemblies',
          'GenerateSerializationAssemblies',
          'GenerateShimsAssets',
          'GenerateSingleFileBundle',
          'GenerateSourceLinkFile',
          'GenerateSupportedRuntime',
          'GenerateSupportedTargetFrameworkAlias',
          'GenerateTargetFrameworkMonikerAttribute',
          'GenerateTargetPlatformDefineConstants',
          'GenerateToolsSettingsFileFromBuildProperty',
          'GetAllRuntimeIdentifiers',
          'GetAssemblyAttributes',
          'GetAssemblyVersion',
          'GetCompile',
          'GetCopyToOutputDirectoryItems',
          'GetCopyToPublishDirectoryItems',
          'GetFrameworkPaths',
          'GetInstalledSDKLocations',
          'GetItemTargetPaths',
          'GetNativeManifest',
          'GetPackagingOutputs',
          'GetPotentialEditorConfigFiles',
          'GetReferenceAssemblyPaths',
          'GetReferenceTargetPlatformMonikers',
          'GetReferencesForApiCompatValidatePackage',
          'GetResolvedSDKReferences',
          'GetSuggestedWorkloads',
          'GetTargetFrameworkDirectories',
          'GetTargetFrameworkMoniker',
          'GetTargetFrameworkMonikerDisplayName',
          'GetTargetFrameworkProperties',
          'GetTargetFrameworkVersion',
          'GetTargetFrameworks',
          'GetTargetFrameworksWithPlatformForSingleTargetFramework',
          'GetTargetPath',
          'GetTargetPathWithTargetPlatformMoniker',
          'ILLink',
          'IgnoreJavaScriptOutputAssembly',
          'IncludeTargetingPackReference',
          'IncludeTransitiveProjectReferences',
          'IncrementalClean',
          'InitializeSourceControlInformation',
          'InitializeSourceControlInformationFromSourceControlManager',
          'InitializeSourceRootMappedPaths',
          'Pack',
          'PackTool',
          'PostBuildEvent',
          'PreBuildEvent',
          'PrepOptimizer',
          'PrepRestoreForStoreProjects',
          'PrepareForBuild',
          'PrepareForBundle',
          'PrepareForComposeStore',
          'PrepareForPublish',
          'PrepareForRun',
          'PrepareProjectReferences',
          'PrepareResourceNames',
          'PrepareResources',
          'PrepforRestoreForComposeStore',
          'PriFilesOutputGroup',
          'ProcessFrameworkReferences',
          'Publish',
          'PublishBuild',
          'PublishContainer',
          'PublishItemsOutputGroup',
          'PublishOnly',
          'Rebuild',
          'ReferenceCopyLocalPathsOutputGroup',
          'RemoveManagedWinRTComponentWinMDReferences',
          'ResGen',
          'ResolveAssemblyReferences',
          'ResolveAssemblyReferencesDesignTime',
          'ResolveCodeAnalysisRuleSet',
          'ResolveComReferences',
          'ResolveComReferencesDesignTime',
          'ResolveFrameworkReferences',
          'ResolveKeySource',
          'ResolveLockFileAnalyzers',
          'ResolveLockFileCopyLocalFiles',
          'ResolveLockFileReferences',
          'ResolveNativeReferences',
          'ResolveOffByDefaultAnalyzers',
          'ResolvePackageAssets',
          'ResolvePackageDependenciesDesignTime',
          'ResolvePackageDependenciesForBuild',
          'ResolveProjectReferences',
          'ResolveProjectReferencesDesignTime',
          'ResolveReadyToRunCompilers',
          'ResolveReferences',
          'ResolveRuntimePackAssets',
          'ResolveSDKReferences',
          'ResolveSDKReferencesDesignTime',
          'ResolveTargetingPackAssets',
          'Restore',
          'RestoreForComposeStore',
          'Run',
          'RunCrossGen',
          'RunPackageValidation',
          'RunProduceContentAssets',
          'RunResolvePackageDependencies',
          'RunResolvePublishAssemblies',
          'SDKRedistOutputGroup',
          'SGenFilesOutputGroup',
          'SGenFilesOutputGroupDependencies',
          'SatelliteDllsProjectOutputGroup',
          'SatelliteDllsProjectOutputGroupDependencies',
          'SetEmbeddedFilesFromSourceControlManagerUntrackedFiles',
          'SetGenerateManifests',
          'SetWin32ManifestProperties',
          'ShimReferencePathsWhenCommonTargetsDoesNotUnderstandReferenceAssemblies',
          'ShowCallOfVSTestTaskWithParameter',
          'ShowInfoMessageIfProjectHasNoIsTestProjectProperty',
          'ShowMsbuildWithParameter',
          'SourceControlManagerPublishTranslatedUrls',
          'SourceFilesProjectOutputGroup',
          'SplitResourcesByCulture',
          'StoreFinalizer',
          'StoreResolver',
          'StoreWorkerMain',
          'StoreWorkerMapper',
          'StoreWorkerPerformWork',
          'TranslateAzureReposGitUrlsInSourceControlInformation',
          'TranslateBitbucketGitUrlsInSourceControlInformation',
          'TranslateGitHubUrlsInSourceControlInformation',
          'TranslateGitLabUrlsInSourceControlInformation',
          'UnmanagedRegistration',
          'UnmanagedUnregistration',
          'UpdateAspNetToFrameworkReference',
          'VSTest',
          'ValidateCommandLineProperties',
          'ValidateExecutableReferences',
          'WarnForExplicitVersions',
          'XamlPreCompile',
        ],
        evaluation: {
          Items: {},
          Properties: {
            TargetFramework: 'netstandard1.0',
            TargetFrameworks: '',
            RuntimeIdentifier: '',
            RuntimeIdentifiers: '',
          },
        },
      })

      deepStrictEqual(actual, expected)
    })
  })
})
