# Inspired by https://github.com/GitTools/GitVersion/blob/main/.github/workflows/ci.yml

name: CI

on:
  push:
    branches-ignore: # Ignore Release branches. The Release workflow will invoke CI
      - main
      - develop
  pull_request:
  workflow_call:

env:
  DOTNET_ROLL_FORWARD: "Major"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/_unit_test.yml # <- your unit test workflow here. Example: file://./_unit_test.yml
