# This workflow demonstrates the minimal requirements for
# building, publishing, and packing a CSharp Project with DotNet CLI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4

    - run: dotnet build src/SPV3.csproj -c Release -p:ContinuousIntegrationBuild=true
      # ContinuousIntegrationBuild comes from dotnet/sourcelink. Make sure Deterministic is also true!
      # Alternatively, add a PropertyGroup with the condition " '$(CI)' != '' "