# footer contains links e.g. 3rd-party plugins, little-known features

### global vars
# https://semantic-release.gitbook.io/semantic-release/v/beta/usage/plugins#plugin-options-configuration
preset: conventionalcommits

### main options

branches: # https://semantic-release.gitbook.io/semantic-release/v/beta/usage/configuration#branches
  - main
  - name: develop
    channel: develop
    prerelease: true
plugins: # https://semantic-release.gitbook.io/semantic-release/v/beta/usage/configuration#plugins
  - "@semantic-release/commit-analyzer"
  - "semantic-release-export-data"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - README.md
        - CHANGELOG.md
  # Arbitrary shell commands - https://github.com/semantic-release/exec
  # hint: set 'prepareCmd' to `dotnet publish`.
  #   Because this is sorted after @semantic-release/git, the new Git tag will 
  #   be visible to dotnet (and GitVersion). Dotnet artifacts will be
  #   versioned accordingly.
  # Plugins' Steps: https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md
  - "@semantic-release/exec"
  - - "@semantic-release/github"
    - assets:
        - path: ./publish/*

## (OPTIONAL) update static Version strings.
# https://github.com/jpoehnelt/semantic-release-replace-plugin
# https://github.com/droidsolutions/semantic-release-update-file
