name: Conventional Pull Request
# See https://github.com/Namchee/conventional-pr

on:
  pull_request:
permissions:
  checks: write
  issues: write
  pull-requests: write

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: conventional-pr
        uses: Namchee/conventional-pr@v0.15.4
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
