# Inspired by https://github.com/GitTools/GitVersion/blob/main/.github/workflows/ci.yml

# Call from your own CI workflow!
# uses: HaloSPV3/HCE.Shared/.github/workflows/dotnet-ci.yml@{branch}
# uses: HaloSPV3/HCE.Shared/.github/workflows/dotnet-ci.yml@{tag}
# uses: HaloSPV3/HCE.Shared/.github/workflows/dotnet-ci.yml@{commit}

name: CI

on:
  # push:
  #   branches-ignore: # if CI must run on these branches, Release will call CI
  #     - main
  #     - develop
  # pull_request:
  workflow_call:

env:
  DOTNET_ROLL_FORWARD: "Major"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/_dotnet-unit_test.yml

  build:
    name: Build
    uses: ./.github/workflows/_dotnet-build.yml
