name: fast-forward merge on label

on:
  pull_request:
    types: [labeled]

jobs:
  echo-base-head-ref:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Ref: ${{ github.head_ref }}"

  fast-forward-merge:
    if: github.event.label.name == 'fast-forward'
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Payload
        run: |
          echo "Event Payload:"
          echo "${{ toJson(github.event) }}"
      - name: Fast Forward PR
        uses: onee-only/ff-merge@1ad46d4
        with:
          allowed-roles: '["maintain"]'
          GITHUB_TOKEN: ${{ secrets.FAST_FORWARD_GITHUB_TOKEN }}