on:
  push:
    # do not run on branches listed in npm-release.yml
    branches-ignore: [main,  develop, next/v3.0.0]
  pull_request:

env:
  CI_PROJECT_ID: 70884695

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: package.json
          check-latest: true
      - uses: actions/cache/restore@v4
        with:
          path: /usr/lib/dotnet
          key: usr-lib-dotnet
      - uses: actions/setup-dotnet@v4
        with:
          # required by Kuinox.NupkgDeterministicator
          dotnet-version: 6.x
          global-json-file: ./global.json
      - uses: actions/cache/save@v4
        with:
          path: /usr/lib/dotnet
          key: usr-lib-dotnet

      - run: npm i -g npm@latest
      - run: npm ci
      - run: npm run pack
      - run: npm run check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GL_TOKEN: ${{ secrets.GL_SEMANTICRELEASE }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
