on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: package.json
          check-latest: true
      - run: npm i -g npm@latest
      - run: npm ci
      - run: npm run pack
      - run: npm run check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GL_TOKEN: ${{ secrets.GL_SEMANTICRELEASE }}
          CI_PROJECT_ID: 70884695
