name: test-npm-install-pack

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        buildConfig: [ "Release", "Debug" ] # example

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
    - run: npm install --save-dev
    - run: npm pack --dry-run --pack-destination ./bin/ # file creation skipped by --dry-run
