name: test-dotnet-build-and-publish
# This workflow demonstrates the minimal requirements for
# building, publishing, and packing a CSharp Project with DotNet CLI

on:
  push:
    paths:
    - '!**/*.md'
    - '!**/*.txt'
  pull_request:

jobs:
  ################
  # BUILD
  ################
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        buildConfig: [ "Release", "Debug" ]
        project: ["SPV3", "HXE" ] #etc

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # SDK Version to use.
        include-prerelease: true

    - name: Build
      working-directory: ./src/
      run: dotnet build ${{ matrix.project }}.csproj -c ${{ matrix.buildConfig }}

  ################
  # BUILD AND PUBLISH
  ################
  publish:
    name: Publish
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        buildConfig: [ "Release", "Debug" ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # SDK Version to use.
        include-prerelease: true

    - name: Build and Publish to directory
      working-directory: ./src/
      run: dotnet publish ${{ matrix.project }}.csproj -c ${{ matrix.buildConfig }}
